language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel # build images
  - docker tag udagram-api-feed Bog0sso/udagram-api-feed:v0  # feed-service image
  - docker tag udagram-api-user Bog0sso/udagram-api-user:v0  # user-service image
  - docker tag udagram-frontend Bog0sso/udagram-frontend:v0  # frontend-service image
  - docker tag reverseproxy Bog0sso/reverseproxy:v0          # reverseproxy image

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push Bog0sso/udagram-api-feed:v0
  - docker push Bog0sso/udagram-api-user:v0
  - docker push Bog0sso/udagram-frontend:v0
  - docker push Bog0sso/reverseproxy:v0