kubectl delete -f env-configmap.yaml
kubectl delete -f env-secret.yaml
kubectl delete -f aws-secret.yaml
kubectl delete -f user-deployment.yaml
kubectl delete -f user-service.yaml
kubectl delete -f feed-deployment.yaml
kubectl delete -f feed-service.yaml
kubectl delete -f reverseproxy-deployment.yaml
kubectl delete -f reverseproxy-service.yaml
kubectl delete -f frontend-deployment.yaml
kubectl delete -f frontend-service.yaml